[project]
name = "ampla_project"
version = "0.1.0"
description = "Ampla project normalization engine"
authors = [
    { name = "Giorgio" }
]
requires-python = ">=3.12"
dependencies = [
    "lxml",
    "fastapi",
    "uvicorn[standard]"
]

[project.optional-dependencies]
test = [
    "pytest",
    "httpx"
]

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
package-dir = { "" = "." }

[tool.setuptools.packages.find]
where = ["."]
include = ["ampla_project*"]

[tool.pytest.ini_options]
pythonpath = ["."]
testpaths = ["tests"]
